networks:
  net:
    external: true

services:
  sharelatex:
    image: sharelatex/sharelatex
    container_name: sharelatex
    restart: unless-stopped

    depends_on:
      mongo:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully
      redis:
        condition: service_started

    ports:
      - "3000:80"

    stop_grace_period: 60s

    volumes:
      - /srv/overleaf/overleaf:/var/lib/overleaf

    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_SITE_URL: ${OVERLEAF_SUBDOMAIN}.${DOMAIN}

      OVERLEAF_MONGO_URL: mongodb://mongo:27017/sharelatex?replicaSet=overleaf

      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis

      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"

      SANDBOXED_COMPILES: "false"
    networks:
      - net

  mongo:
    image: mongo:8
    container_name: mongo
    restart: unless-stopped

    command: ["--replSet", "overleaf", "--bind_ip_all"]

    volumes:
      - /srv/overleaf/mongo:/data/db

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks:
      - net

  mongo-init:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_started
    restart: "no"

    entrypoint: >
      bash -c "
        echo 'Waiting for Mongo...';
        until mongosh --host mongo --eval 'db.adminCommand(\"ping\")' >/dev/null 2>&1; do
          sleep 2;
        done;

        echo 'Initializing replica set...';
        mongosh --host mongo --eval '
          try {
            rs.initiate({
              _id: \"overleaf\",
              members: [{ _id: 0, host: \"mongo:27017\" }]
            })
          } catch(e) {
            print(e);
          }
        ';
      "

    networks:
      - net

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped

    volumes:
      - /srv/overleaf/redis:/data
    
    networks:
      - net